// methods and pointer indirection

// functions with pointer args
// MUST take a pointer

// methods with pointer receivers
// accept both values AND pointers
// though this is because the pointer
// is autogenerated

package main

import "fmt"

type Vertex struct {
	X, Y float64
}

// method
func (v *Vertex) Scale(f float64) {
	v.X = v.X * f
	v.Y = v.Y * f
}

func ScaleFunc(v *Vertex, f float64) {
	v.X = v.X * f
	v.Y = v.Y * f
}

func main() {
	v := Vertex{3, 4}
	// note the next line is
	// read as (&v).Scale(2)
	// the pointer is autogenerated
	v.Scale(2)
	ScaleFunc(&v, 10)

	p := &Vertex{4, 3}
	p.Scale(3)
	ScaleFunc(p, 8)

	fmt.Println(v, p)
}
